site_name: Vuelto
site_description: A fast and lightweight game engine powered by Go and OpenGL. Easy, fast and lightweight!
site_url: https://vuelto.pp.ua
site_author: The Vuelto Team
copyright: The Vuelto Team

repo_name: vuelto-org/vuelto
repo_url: https://github.com/vuelto-org/vuelto

docs_dir: "website"

nav:
  - Home: "index.md"
  - Getting started:
      - 🚀 Quick start: "get-started.md"
      - 🛠️ In-depth Installation: "install.md"

  - Docs:
      - 🏠 Docs: "docs/index.md"
      - 👤 User Docs:
          - 🖥️ Windowing and Renderer: "docs/latest/window-render.md"
          - 🔊 Audio: "docs/latest/audio.md"
          - 🔥 Events: "docs/latest/events.md"
          - 🖼️ Images: "docs/latest/image.md"
          - 🎨 Drawing: "docs/latest/draw.md"
          - 🔢 Vector Math: "docs/latest/vectors.md"
      - 📱 Developer Docs:
          - 💻 Dev Home: "docs/developers/index.md"
          - 💍 3 Ring approach: "docs/developers/rings.md"
          - 📋 Contribution Guidelines: "docs/developers/contribution.md"

  - Blog:
      - blog/index.md

  - Tutorials:
      - 🎓 Tutorials: "tutorials/index.md"
      - 🌱 Beginner:
          - 🚀 Getting Started: "tutorials/beginner/new-project.md"
          - 🎨 Rendering: "tutorials/beginner/rendering.md"
  - Demo:
      - 🏠 Demo: "demo/index.md"
      - 📚 Shapes: "demo/1/index.html"
      - 📚 Images: "demo/2/index.html"
      - 📚 Rendering: "demo/3/index.html"

  - Roadmap:
      - 📅 Upcoming: "roadmap/index.md"
      - 🛣️ V1: "roadmap/v1.md"
      - 🛣️ V2: "roadmap/v2.md"

  - About:
      - 🛈 About: "about/index.md"
      - 🛡️ License: "about/license.md"
      - 🤝 Code of Conduct: "about/coc.md"
      - 👥 Contributing: "about/contributing.md"

theme:
  name: material
  custom_dir: website/overrides

  logo: /logo/pfp-nobg.png
  favicon: logo/favicon.png

  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - navigation.expand

    - content.code.copy

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep-orange # close to vuelto orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo # close to vuelto blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  version:
    provider: mike

plugins:
  - blog
  - redirects:
      redirect_maps:
        "discord.md": "https://discord.gg/gZqdRXbbqg"
        "repo.md": "https://github.com/vuelto-org/vuelto"
        "examples.md": "demo/index.md"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.emoji:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
