authors:
  zaka:
    name: Zaka
    description: Vuelto Team
    avatar: https://0.gravatar.com/avatar/97d096fa42833c482e4e2f5636421ac224790ff071e431e59448f01e27dce5d2?size=512
  dima:
    name: Dima
    description: Vuelto Founder
    avatar: https://0.gravatar.com/avatar/fedd02035b89edb60561816884bbb996?size=512
